---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность добавлять товары в корзину и продолжать выбирать товары в каталоге
  - Пользователь должен иметь возможность изменять количество содержимого корзины и просматривать содержимое корзины
  - Пользователь должен иметь возможность удалять содержимое корзины  
  - Пользователь должен иметь возможность из корзины вернуться на главную страницу
  - Пользователь имеет возможность оформить заказ из корзины
  - Пользователь может перемещаться по страницам каталога сайта
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть доступен и корректно отображаться в различных браузерах
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - На странице товара и в каталоге нужно выводить данные о товаре (название, рейтинг, цена со скидкой и без нее)
  - Корзина пользователя должна сохраняться в текущей сессии браузера
implicit:
  - Сайт должен функционировать на русском и английйском языках
  - При добавлении товара в корзину должен изменяться остаток товара в магазине
  - Должна быть добавлена форма обратной связи от клиента 
  - Пользователь не должен иметь возможность редактировать описание товара
  - Сайт должен автоматически предотврашать возможность фильтрации цен с отрицательным значением
